// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD22BPHVUyX1UDJ9iC_BhAuuPaJRMochJ8',
    appId: '1:948861459344:web:5cf49ded66f5add4f97115',
    messagingSenderId: '948861459344',
    projectId: 'freecode-mohamed',
    authDomain: 'freecode-mohamed.firebaseapp.com',
    storageBucket: 'freecode-mohamed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB_uw9cilRIMj0FxgzkSphFzSmwiB5anY',
    appId: '1:948861459344:android:3b70be1b619a018cf97115',
    messagingSenderId: '948861459344',
    projectId: 'freecode-mohamed',
    storageBucket: 'freecode-mohamed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGMCdeikgHrSdkUckeGWmHF5XBC1het_I',
    appId: '1:948861459344:ios:05ed672508709b3ff97115',
    messagingSenderId: '948861459344',
    projectId: 'freecode-mohamed',
    storageBucket: 'freecode-mohamed.appspot.com',
    iosBundleId: 'com.example.freecodecamp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGMCdeikgHrSdkUckeGWmHF5XBC1het_I',
    appId: '1:948861459344:ios:450cd4a7f51f969df97115',
    messagingSenderId: '948861459344',
    projectId: 'freecode-mohamed',
    storageBucket: 'freecode-mohamed.appspot.com',
    iosBundleId: 'com.example.freecodecamp.RunnerTests',
  );
}
